add `#[track_caller]` to test wrapper
this makes it easier to identify what test failed, pointing to the caller of wrapper instead of the wrapper fn

```
panicked at 'the test failed', src/web/rustdoc.rs:line:col
```