Don't discard errors from r2d2 when printing error chain
Previously:
```
Error: failed to create the database connection pool

Caused by:
    failed to create the database connection pool
```

Now:
```
Error: failed to create the database connection pool

Caused by:
    failed to create the database connection pool

Caused by:
    timed out waiting for connection: error connecting to server: Connection refused (os error 111)
```