Don't execute a build when not enough memory is available
Example error:

```
2021/02/15 01:43:12 [INFO] docs_rs::docbuilder::rustwide_builder: building package regex 1.3.1
Error: Building documentation failed

Caused by:
    not enough memory to build regex 1.3.1: needed 3072 MiB, have 2909 MiB
help: set DOCSRS_DISABLE_MEMORY_LIMIT to force a build
```